sudo: false
language: scala
scala:
  - 2.12.2
jdk:
  - openjdk8

stages:
  - name: build
  - name: publish
    if: ((branch = master) AND (type != pull_request)) OR (tag IS present)

jobs:
  include:
    - stage: build
      script: sbt ++$TRAVIS_SCALA_VERSION test

env:
  global:
    - secure: "UrFYn6hP0Tci4IBZXOu3KE9L0DUzKzgDHIoh3qCOdekBiKTlcqC//F3i8vMKcJ6+fBF7Ov7LzlDKdu3CMJ7lUMmpxyOt+8QEmxjko73A0Fy3CbuIFl98a26kP6xdPwkZYieCpddtIKdYTa+33Ipv0OL2mw0tgjdpfUidC7cIzEjTIPY8bhw6v08TP1o2HSyLy6/54HSshXDnUogpirWgyoMn4Nneb4Ki7QEHosm1nDGcHHBCpgsHzn31TqB5kFo3U7ZRY6plBxoB506cPY3HvtStHCh7VL2rV77T3/NX8IALLS7UYF8ysdPe5WF/RTQpfioVTuyLlKklAAY/NrdDXRLUVS1CEP/4O+xPrHQrZe+mrVVMFrtDqPAYOLm08R5dKl1pSSNc8ZX08XezGrNG4wO4kYAHJZPT+gIl/hS+ITQstHqlq2et7pREIMvp7Mco78sMonPzcRlnLmHxqz7zLChnZMD6TPVMIagziKnYE6Z/9eni2DrJF4mutncfDt1A4o4ssjoN3V0qGkWpWATPPN7PIbMDg+l62lW2OpFv6xhPXNwBaa2xhsAafa55w0K9jG7uIkpqyQs7oW52G0q3MGQRW14FZnzA5MuobVT9UiC7/iSYLfNORrIQg1m1QO65757xYr6Pt5UoalRtdTQ3AlZs2jjTAkjtQe1E6lix1Zs="
    - secure: "Aua13r2PxTgpH21uhYtf7/ZfHBGI2mkHUAJWmpZ91PKKiuy4J/hkoZOHJOCjegFLAX4U9JWDmxbyMc+te094kOi4DKPIIvebKccjuqZRQD69/qcOZcERJKIoVaWjXBmXD9S0s6FBvSD1JPSujJ5S7MszOk6ilhoPSlvry3jvyAjX5w6hW6jZLysT1/ilsghdJCAFiqhskTwvIMWpUxh57THqwLAv45G17eeP2ruDRO2gZkgujaxXZBtiez4dIIrPgvg6jsSVJ46RGu539wyjQbAWaWYlCWboSrBcAChFLBKrSqGFOYD5w8PfFVSYvsKoHt/eeY9/xMbSxlGgAuC6w2LrRQGOz0PNqGeweYU4u8bMC0l58E+KhYuE30YFKGug+oua+c+9fT+WMdT0U5SdkOoVxF0MVZIZ7lGNTUZP52bTlko9NSKBPv3lNHuUPEbwPPD8sECmz39Kld9LyOSdHNsJ6GL0/jShQbUrdIOV28zF3OKZUPBq9pOcDPVhuzYNfM5FU0JaCrO5180ExqDXe6A33lAB0Nwaxx7zbR+rkBz0lTDISHGqachdskpCHQQpmL7C1BYxvYFivI1B1Ac/rk/bUE6CY2Vb5ggMJfa4Q05ioV1onj6d2r2POqq3Jbb5AU662DVGn+4n2cWxssi0tDzQR4iSFbv9DkNfmdp8ESQ="
    - secure: "ZwGuIqO7zQG7sW3FMp0is6v2H6kWuNjLmgL1qyL/mDCXQChOqj8qTAs8PBd6Lv+v5iA/GJMmZmcR4gsTaielRJk8HpmW013ZWUrJVHcLKAiUQ47b0m5vzVWDavoQqPif6ZlFMEwiUYR0Oz7mvo7pC6pKcUfiC6wTsfaMN6+4ArvULbjeA1W9/G78qIGoqiTlWfmtu8dBXZ3QlaoCbxhyHTxxAl1oFOBzxR6L8AQ7q9kCMCukDIzYt/gnmbyDr8lzakNQ/gwjWIQr/q0ZlbNOZZNtWxAhIVi/im/dLuZwNNLAVjkgUvkAghqGY/3hhylZ9WdzTw1e4IRTAg4gtKNvffJ/+XWOKv4S3hgd9SwmI89idzbFqi503k6YRDscv8nVodIr22u6bqKJNLmKBhZZ9Er5v2TmORCm7/cuywhaXOr0HFwjy6zkRI/pm73jIJl+9mYR9NcFgopSZLgl4ZH9yr+01o6HAKGIEz1/kgwN1YR0HQRtTUSTy2I0R6zaBaQVSI1RKdfeFh/zxPvIlgmml+7eMyQparxUcd5trAmM9V1jU49udI8XN9QZbYbvO3XrbyfFQLCZ6KU9ZiB5YNXDjLHDYkLItn89meznaojpUxCu1Je3NvhNQ+IcbOXaTTzlQSicptU8TXsvbzO2GmbkiiPxZXhREhFA5y/pNxGxdzI="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier