sudo: false
language: scala
scala:
  - 2.12.2
jdk:
  - openjdk8

stages:
  - name: build
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: build
      script: sbt ++$TRAVIS_SCALA_VERSION scripted
    - stage: publish
      script: sbt ++$TRAVIS_SCALA_VERSION releaseEarly;

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_7edee92045c5_key -iv $encrypted_7edee92045c5_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
    fi
env:
  global:
    - secure: "dX0/0svIVfDh7Ush3m+ryNmLO3RJJGHr2d6E6hZjPYqwdH4cjkeov1Va+hs6KGz3rAG8DqbweQ7RR+S1IoEg257y+v7t64eKFm0w9rYWV0jbvhTi7xdaU5SVrevQ7HqEr9/mNd35VFYbZ14VPBM5Pm1y9SWmlO6qvbbu9MLxurVqq/z2YUdHKrFW8mZh8n/PEZCmc+I/gTWNWrPsl7UuQ9+R/vAEkwIsU/DuP5BdH70vYVQsgyry+ZQyyyEFtETFEWdP3kR63d1Ws0+ACse2v8vYKaL7lRdo+YgdFxOY1d4qjQ8P6H+MR3TjejJzuZDCA42NJh9y48iWZUxWNwJb5WBH2cL3RPjZURGSFEnjIjxTF7Ser08Xu7OpJ8rj4vLGyF9ovcDDaA7FDvTrgE3cORuxsuZFEjo7PLvs8OjgWZ866wQVVD38yCODQa+dmg2+aN1kXoiVBH6q28GWT6cNM43zk2/jlNKwv8IvDanBlGQ5SuHKdTJ1NBl8ojmwaITBZkmUNqSwSER8fjXT92S5X+JXSEClN13odDfic9zEHggDTsdkXoAdkcFL3TFbxahEqkD5KHOtsNN5jKo34GcLPMft/cc/0aLcsKuEhydR10kBWQqfIIT0fbsOKntI1MFGd3JFyY1xu0hDMd+tRh8td7YqZs+JSZ2Be+f+8FkTY7Y="
    - secure: "Aua13r2PxTgpH21uhYtf7/ZfHBGI2mkHUAJWmpZ91PKKiuy4J/hkoZOHJOCjegFLAX4U9JWDmxbyMc+te094kOi4DKPIIvebKccjuqZRQD69/qcOZcERJKIoVaWjXBmXD9S0s6FBvSD1JPSujJ5S7MszOk6ilhoPSlvry3jvyAjX5w6hW6jZLysT1/ilsghdJCAFiqhskTwvIMWpUxh57THqwLAv45G17eeP2ruDRO2gZkgujaxXZBtiez4dIIrPgvg6jsSVJ46RGu539wyjQbAWaWYlCWboSrBcAChFLBKrSqGFOYD5w8PfFVSYvsKoHt/eeY9/xMbSxlGgAuC6w2LrRQGOz0PNqGeweYU4u8bMC0l58E+KhYuE30YFKGug+oua+c+9fT+WMdT0U5SdkOoVxF0MVZIZ7lGNTUZP52bTlko9NSKBPv3lNHuUPEbwPPD8sECmz39Kld9LyOSdHNsJ6GL0/jShQbUrdIOV28zF3OKZUPBq9pOcDPVhuzYNfM5FU0JaCrO5180ExqDXe6A33lAB0Nwaxx7zbR+rkBz0lTDISHGqachdskpCHQQpmL7C1BYxvYFivI1B1Ac/rk/bUE6CY2Vb5ggMJfa4Q05ioV1onj6d2r2POqq3Jbb5AU662DVGn+4n2cWxssi0tDzQR4iSFbv9DkNfmdp8ESQ="
    - secure: "ZwGuIqO7zQG7sW3FMp0is6v2H6kWuNjLmgL1qyL/mDCXQChOqj8qTAs8PBd6Lv+v5iA/GJMmZmcR4gsTaielRJk8HpmW013ZWUrJVHcLKAiUQ47b0m5vzVWDavoQqPif6ZlFMEwiUYR0Oz7mvo7pC6pKcUfiC6wTsfaMN6+4ArvULbjeA1W9/G78qIGoqiTlWfmtu8dBXZ3QlaoCbxhyHTxxAl1oFOBzxR6L8AQ7q9kCMCukDIzYt/gnmbyDr8lzakNQ/gwjWIQr/q0ZlbNOZZNtWxAhIVi/im/dLuZwNNLAVjkgUvkAghqGY/3hhylZ9WdzTw1e4IRTAg4gtKNvffJ/+XWOKv4S3hgd9SwmI89idzbFqi503k6YRDscv8nVodIr22u6bqKJNLmKBhZZ9Er5v2TmORCm7/cuywhaXOr0HFwjy6zkRI/pm73jIJl+9mYR9NcFgopSZLgl4ZH9yr+01o6HAKGIEz1/kgwN1YR0HQRtTUSTy2I0R6zaBaQVSI1RKdfeFh/zxPvIlgmml+7eMyQparxUcd5trAmM9V1jU49udI8XN9QZbYbvO3XrbyfFQLCZ6KU9ZiB5YNXDjLHDYkLItn89meznaojpUxCu1Je3NvhNQ+IcbOXaTTzlQSicptU8TXsvbzO2GmbkiiPxZXhREhFA5y/pNxGxdzI="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier